#!/bin/bash
# =============================================================
# aks-pcap-tool — Dry Run Test Suite
# Tests script logic without a real AKS cluster
# =============================================================

PASS=0
FAIL=0
SCRIPT_PATH="$(dirname "$0")/../scripts/aks-pcap-capture.sh"

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

echo ""
echo -e "${CYAN}${BOLD}============================================${RESET}"
echo -e "${CYAN}${BOLD}   aks-pcap-tool — Dry Run Test Suite      ${RESET}"
echo -e "${CYAN}${BOLD}============================================${RESET}"
echo ""

# =============================================================
# Helper functions
# =============================================================

pass() {
  echo -e "  ${GREEN}✓ PASS${RESET} — $1"
  PASS=$((PASS + 1))
}

fail() {
  echo -e "  ${RED}✗ FAIL${RESET} — $1"
  FAIL=$((FAIL + 1))
}

section() {
  echo ""
  echo -e "${YELLOW}${BOLD}$1${RESET}"
}

# =============================================================
# TEST 1 — Script exists
# =============================================================

section "[1] Script Validation"

if [ -f "$SCRIPT_PATH" ]; then
  pass "Script file exists at $SCRIPT_PATH"
else
  fail "Script not found at $SCRIPT_PATH"
fi

# =============================================================
# TEST 2 — Script is executable
# =============================================================

if [ -x "$SCRIPT_PATH" ]; then
  pass "Script is executable"
else
  fail "Script is not executable — run: chmod +x $SCRIPT_PATH"
fi

# =============================================================
# TEST 3 — Script contains required functions/flags
# =============================================================

section "[2] Script Content Checks"

grep -q "snapshot-length=0" "$SCRIPT_PATH" && \
  pass "tcpdump --snapshot-length=0 flag present (full packet capture)" || \
  fail "Missing --snapshot-length=0 flag"

grep -q "\-vvv" "$SCRIPT_PATH" && \
  pass "tcpdump -vvv flag present (verbose output)" || \
  fail "Missing -vvv flag"

grep -q "hostNetwork: true" "$SCRIPT_PATH" && \
  pass "hostNetwork: true present (node-level capture)" || \
  fail "Missing hostNetwork: true"

grep -q "privileged: true" "$SCRIPT_PATH" && \
  pass "privileged: true present (required for tcpdump)" || \
  fail "Missing privileged: true"

grep -q "nicolaka/netshoot" "$SCRIPT_PATH" && \
  pass "nicolaka/netshoot image referenced" || \
  fail "Missing nicolaka/netshoot image"

grep -q "HOW_TO_SHARE_WITH_SUPPORT" "$SCRIPT_PATH" && \
  pass "Support instructions file is generated" || \
  fail "Missing HOW_TO_SHARE_WITH_SUPPORT output"

grep -q "kubectl delete pod" "$SCRIPT_PATH" && \
  pass "Debug pod cleanup present" || \
  fail "Missing debug pod cleanup"

# =============================================================
# TEST 4 — Mock kubectl and simulate output folder creation
# =============================================================

section "[3] Output Folder Simulation"

TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
TEST_OUTPUT_DIR="/tmp/aks-pcap-test-${TIMESTAMP}"
TEST_PCAP="${TEST_OUTPUT_DIR}/capture_${TIMESTAMP}.pcap"
TEST_INSTRUCTIONS="${TEST_OUTPUT_DIR}/HOW_TO_SHARE_WITH_SUPPORT.txt"

mkdir -p "$TEST_OUTPUT_DIR"

if [ -d "$TEST_OUTPUT_DIR" ]; then
  pass "Output directory created successfully"
else
  fail "Could not create output directory"
fi

# Simulate pcap file creation
touch "$TEST_PCAP"
if [ -f "$TEST_PCAP" ]; then
  pass "Capture file placeholder created"
else
  fail "Could not create capture file"
fi

# Simulate instructions file creation
cat > "$TEST_INSTRUCTIONS" << EOF
TEST — HOW_TO_SHARE_WITH_SUPPORT.txt
Generated by dry-run test at $TIMESTAMP
EOF

if [ -f "$TEST_INSTRUCTIONS" ]; then
  pass "HOW_TO_SHARE_WITH_SUPPORT.txt created successfully"
else
  fail "Could not create instructions file"
fi

# =============================================================
# TEST 5 — Mock kubectl node lookup
# =============================================================

section "[4] Mock kubectl Checks"

# Create a temporary mock kubectl
MOCK_BIN="/tmp/mock-kubectl-${TIMESTAMP}"
cat > "$MOCK_BIN" << 'EOF'
#!/bin/bash
if [[ "$*" == *"jsonpath"* ]]; then
  echo "aks-nodepool1-12345678-vmss000000"
elif [[ "$*" == *"current-context"* ]]; then
  echo "my-test-cluster"
else
  echo "mock-kubectl: $*"
fi
EOF
chmod +x "$MOCK_BIN"

# Test mock kubectl returns a node name
NODE=$("$MOCK_BIN" get pod test-pod -n default -o jsonpath='{.spec.nodeName}')
if [ "$NODE" = "aks-nodepool1-12345678-vmss000000" ]; then
  pass "Mock kubectl node lookup returns expected node name"
else
  fail "Mock kubectl node lookup failed — got: $NODE"
fi

# Test mock kubectl returns a context
CONTEXT=$("$MOCK_BIN" config current-context)
if [ "$CONTEXT" = "my-test-cluster" ]; then
  pass "Mock kubectl context check returns expected context"
else
  fail "Mock kubectl context check failed — got: $CONTEXT"
fi

# =============================================================
# TEST 6 — Cleanup simulation
# =============================================================

section "[5] Cleanup Simulation"

rm -rf "$TEST_OUTPUT_DIR"
if [ ! -d "$TEST_OUTPUT_DIR" ]; then
  pass "Output directory cleaned up successfully"
else
  fail "Output directory was not cleaned up"
fi

rm -f "$MOCK_BIN"
if [ ! -f "$MOCK_BIN" ]; then
  pass "Mock kubectl binary cleaned up successfully"
else
  fail "Mock kubectl binary was not cleaned up"
fi

# =============================================================
# RESULTS
# =============================================================

echo ""
echo -e "${CYAN}${BOLD}============================================${RESET}"
echo -e "${BOLD}Results: ${GREEN}${PASS} passed${RESET} / ${RED}${FAIL} failed${RESET}"
echo -e "${CYAN}${BOLD}============================================${RESET}"
echo ""

if [ "$FAIL" -eq 0 ]; then
  echo -e "${GREEN}${BOLD}All tests passed. Script is ready.${RESET}"
  exit 0
else
  echo -e "${RED}${BOLD}${FAIL} test(s) failed. Review output above.${RESET}"
  exit 1
fi
